[project]
name = "django-object-view"
version = "0.1.0"
description = "Library to show Django object properties in groups with customizable templates with focus on bootstrap5"
requires-python = ">=3.13"
dependencies = []
